### ISSUE TITLE
Versioning issues

### ISSUE THREAD

**Issue by Mzngit** [invoiceninja/dockerfiles#112]
Sorry again but after upgrade to invoiceninja/invoiceninja:latest, Docker container ENV variables is correct, stating version 4.5.15
However, the version on the bottom of the actual app once loaded via the web still reads 4.5.14.
Thanks.

**Comment by anojht** [comment]
Hello I noticed the same thing. When I investigated it turns out the download URL regardless of version specified only downloads the 4.5.14.zip file as I believe that URL has not had the latest version uploaded yet. `https://download.invoiceninja.com/ninja-v${INVOICENINJA_VERSION}.zip`

Even if you visit [invoiceninja.org](https://www.invoiceninja.org/) the big green download button says 4.5.14. @hillelcoren The website and download links need to be updated OR the dockerfile will need to be reconfigured to pull from the Github release URL for reliability?

**Comment by hillelcoren** [comment]
v4.5.15 has not yet been released as a self host zip, release are first made available on GitHub.

**Comment by anojht** [comment]
I see thanks. Would there be any issues if I switched to the Github release URL for the container I maintain for invoiceninja? I am just wondering what is the best possible way to offer the latest release to the public.

**Comment by hillelcoren** [comment]
I'd advise against it, we wait to ensure stability before creating the self host zip.

**Comment by anojht** [comment]
Understood. I will wait, again thanks for continuing to maintain an open source project for a really great piece of software!

**Comment by emorydunn** [comment]
I'm running into the same issue, even now that 4.5.16 has been released. It looks like because the image was built before 4.5.16 was available the image actually has 4.5.14. Can the image be re-built so it pulls the latest download?

**Comment by lalop** [comment]
there is a new tag, this one use the last release

**Comment by codedge** [comment]
@lalop 
Is there something left here to be done?

**Comment by lalop** [comment]
last image is version 4.5.18, so yes we can close this issue
