### ISSUE TITLE
Don't run InvoiceNinja as root user

### ISSUE THREAD

**Issue by alexanderadam** [invoiceninja/dockerfiles#99]
It would be nice if the Dockerfiles would use non privileged users instead of root where possible.

For example [like described here](https://medium.com/@mccode/processes-in-containers-should-not-run-as-root-2feae3f0df3b).

**Comment by codedge** [comment]
Please use the current `alpine` image where this issues has been fixed. Also do [note the permission changes](https://github.com/invoiceninja/dockerfiles#create-folders-for-data-persistence) that come with that change.

**Comment by alexanderadam** [comment]
I moved to anotherThank you but in the meantime I moved away to another FOSS invoicing/time tracking solution.

**Comment by codeagencybe** [comment]
@alexanderadam 

What are you using now? And does it support proforma invoice (another thing InvoiceNinja can't handle) ?

**Comment by alexanderadam** [comment]
@codeagencybe I switched to [kimai2](https://github.com/kevinpapst/kimai2). There's also a [demo](https://www.kimai.org/demo/) if you want to try it.
I needed LDAP support which [invoiceninja still hasn't](https://github.com/invoiceninja/invoiceninja/issues/1768).

I'm sure that there might even better solutions. Just look explore GitHub a bit.

For instance search for [`invoicing`](https://github.com/topics/invoicing), [`invoice`](https://github.com/topics/invoice), [`billing`](https://github.com/topics/billing) or [`time-tracking`](https://github.com/topics/time-tracking). There are _a lot_ alternatives (and those are just the projects that are properly tagged). Also CRMs like [dolibarr](https://github.com/Dolibarr/dolibarr), [UltimateCRM](https://github.com/shivampaw/UltimateCRM) or [odoo](https://github.com/odoo/odoo).

Those are looking great as well but I didn't test them:
* [SolidInvoice](https://github.com/SolidInvoice/SolidInvoice) ([demo](http://demo.solidinvoice.co/))
* [InvoicePlane](https://github.com/InvoicePlane/InvoicePlane) ([website](https://www.invoiceplane.com/))
* [open-source-billing](https://github.com/vteams/open-source-billing) ([demo](http://demo.opensourcebilling.org/users/sign_in))
* [invoiceneko](https://github.com/poowf/invoiceneko) ([website](https://invoiceneko.com/features))
* [crater](https://github.com/bytefury/crater) ([website](https://craterapp.com/)) (this is beautiful! check out [the demo](https://demo.craterapp.com/))
* [siwapp](https://github.com/siwapp/siwapp) ([website](http://www.siwapp.com/))

It would be great if you could write me an email or so if you decided for something or found something great. I'm a user who easily changes products if there's something better. :wink:

**Comment by codeagencybe** [comment]
I knew most of these tools already. I was also checking out Crater but it's too limited, no time tracking etc... . 

At the moment. we are using Odoo Enterprise since many years. Mostly because of all their apps integrated. But Odoo is a difficult one in terms of updates but pretty solid. 
It's an ERP after all, not just an invoicing tool. 
For my own company use, we will stay on Odoo for the time being. 

But I was looking around for solutions which we can present to our customers that don't require too complex tools. 
For that InvoiceNinja fit's perfectly. They can handle quotes, invoicing, projects, subscriptions, tasks and tracking. 

But the big down issue for me is no support for proforma invoices. 
In Europe it is very common to sent a proforma invoice, which is just a "draft" invoice copy with no invoice number as this document is not officially booked yet in accounting. 
If a customer decides not to proceed, you can just delete the document and throw in trash, no harm done. No administration work with credit notes etc... because once you book the invoice, the invoice number is issued and the only way to get rid of it is creating credit notes. 

We run a big number of subscriptions for hosting, maintenance etc... 
If customers decide not to renew, we end up with tons of invoices that need manual credit invoice. 
It's a complete normal procedure in Europe, but InvoiceNinja does not has it and seems to be completely blind and deaf to the request from community to have this feature. 
Hence my reason to look for other solutions as this is really mandatory for us.  

So far, I think your best bet is Odoo...

**Comment by hillelcoren** [comment]
This isn't the best place to discuss our competitors, it doesn't seem like a very nice thing to do...
